# Generated by Django 5.0.6 on 2024-06-04 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surat_menyurat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='surat',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
