# Generated by Django 5.0.6 on 2024-06-04 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surat_menyurat', '0002_alter_surat_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suratkeluar',
            name='status',
            field=models.CharField(choices=[('Sudah Dikirim', 'Sudah Dikirim'), ('Diproses ke Kepala Dinas', 'Diproses ke Kepala Dinas'), ('Diproses ke Sekretaris Dinas', 'Diproses ke Sekretaris Dinas'), ('Diproses bidang terkait', 'Diproses Bidang Terkait')], max_length=255),
        ),
        migrations.AlterField(
            model_name='suratmasuk',
            name='status',
            field=models.CharField(choices=[('Baru Masuk', 'Masuk'), ('Diproses ke Kepala Dinas', 'Diproses ke Kepala Dinas'), ('Diproses ke Sekretaris Dinas', 'Diproses ke Sekretaris Dinas'), ('Diproses bidang terkait', 'Diproses Bidang Terkait')], max_length=255),
        ),
    ]
