# Generated by Django 5.0.6 on 2024-06-04 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surat_menyurat', '0003_alter_suratkeluar_status_alter_suratmasuk_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='surat',
            name='file_path',
            field=models.FileField(blank=True, null=True, upload_to='media'),
        ),
    ]
